server:
  port: 9293

spring:
  application:
    name: greetingsuserinfozuulgateway
      
zuul:
  routes:
    greetingsinfofeignclient:
      path: /feign/**
      stripPrefix: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7172/eureka/    
        